#include <stdio.h>
#include <limits.h>
#include "../main.h"

/**
 * main - Entry point
 *
 * Return: Always 0
 */
int main (void)
{
	long l;
	int n;

	puts("[My `_printf`]");
	puts("=========");

	n = _printf("%+d\n", 1024);
	printf("n: %d\n", n);
	n = _printf("%+d\n", -1024);
	printf("n: %d\n", n);
	n = _printf("%+d\n", 0);
	printf("n: %d\n", n);
	n = _printf("%+d\n", INT_MAX);
	printf("n: %d\n", n);
	n = _printf("%+d\n", INT_MIN);
	printf("n: %d\n", n);
	l = INT_MAX + 1024;
	n = _printf("%+d\n", l); /* where l is a long int equals to INT_MAX + 1024 */
	printf("n: %d\n", n);
	l = INT_MIN - 1024;
	n = _printf("%+d\n", l); /* where l is a long int equals to INT_MIN - 1024 */
	printf("n: %d\n", n);
	n = _printf("There is %+d bytes in %+d KB\n", 1024, 1);
	printf("n: %d\n", n);
	n = _printf("%+d - %+d = %+d\n", 1024, 2048, -1024);
	printf("n: %d\n", n);
	n = _printf("%+d + %+d = %+d\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX));
	printf("n: %d\n", n);
	n = _printf("%+i\n", 1024);
	printf("n: %d\n", n);
	n = _printf("%+i\n", -1024);
	printf("n: %d\n", n);
	n = _printf("%+i\n", 0);
	printf("n: %d\n", n);
	n = _printf("%+i\n", INT_MAX);
	printf("n: %d\n", n);
	n = _printf("%+i\n", INT_MIN);
	printf("n: %d\n", n);
	l = INT_MAX + 1024;
	n = _printf("%+i\n", l); /* where l is a long int equals to INT_MAX + 1024 */
	printf("n: %d\n", n);
	l = INT_MIN - 1024;
	n = _printf("%+i\n", l); /* where l is a long int equals to INT_MIN - 1024 */
	printf("n: %d\n", n);
	n = _printf("There is %+i bytes in %+i KB\n", 1024, 1);
	printf("n: %d\n", n);
	n = _printf("%+i - %+i = %+i\n", 1024, 2048, -1024);
	printf("n: %d\n", n);
	n = _printf("%+i + %+i = %+i\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX));
	printf("n: %d\n", n);
	n = _printf("% d\n", 1024);
	printf("n: %d\n", n);
	n = _printf("% d\n", -1024);
	printf("n: %d\n", n);
	n = _printf("% d\n", 0);
	printf("n: %d\n", n);
	n = _printf("% d\n", INT_MAX);
	printf("n: %d\n", n);
	n = _printf("% d\n", INT_MIN);
	printf("n: %d\n", n);
	l = INT_MAX + 1024;
	n = _printf("% d\n", l); /* where l is a long int equals to INT_MAX + 1024 */
	printf("n: %d\n", n);
	l = INT_MIN - 1024;
	n = _printf("% d\n", l); /* where l is a long int equals to INT_MIN - 1024 */
	printf("n: %d\n", n);
	n = _printf("There is % d bytes in % d KB\n", 1024, 1);
	printf("n: %d\n", n);
	n = _printf("% d - % d = % d\n", 1024, 2048, -1024);
	printf("n: %d\n", n);
	n = _printf("% d + % d = % d\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX));
	printf("n: %d\n", n);
	n = _printf("% i\n", 1024);
	printf("n: %d\n", n);
	n = _printf("% i\n", -1024);
	printf("n: %d\n", n);
	n = _printf("% i\n", 0);
	printf("n: %d\n", n);
	n = _printf("% i\n", INT_MAX);
	printf("n: %d\n", n);
	n = _printf("% i\n", INT_MIN);
	printf("n: %d\n", n);
	l = INT_MAX + 1024;
	n = _printf("% i\n", l); /* where l is a long int equals to INT_MAX + 1024 */
	printf("n: %d\n", n);
	l = INT_MIN - 1024;
	n = _printf("% i\n", l); /* where l is a long int equals to INT_MIN - 1024 */
	printf("n: %d\n", n);
	n = _printf("There is % i bytes in % i KB\n", 1024, 1);
	printf("n: %d\n", n);
	n = _printf("% i - % i = % i\n", 1024, 2048, -1024);
	printf("n: %d\n", n);
	n = _printf("% i + % i = % i\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX));
	printf("n: %d\n", n);
	n = _printf("% +i + %+ i = % +d\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX));
	printf("n: %d\n", n);
	n = _printf("% +d + %+ d = % +i\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX));
	printf("n: %d\n", n);
	n = _printf("%#o\n", 1024);
	printf("n: %d\n", n);
	n = _printf("%#o\n", 0);
	printf("n: %d\n", n);
	n = _printf("%#o\n", UINT_MAX);
	printf("n: %d\n", n);
	n = _printf("%#x\n", 1024);
	printf("n: %d\n", n);
	n = _printf("%#x\n", 0);
	printf("n: %d\n", n);
	n = _printf("%#x\n", UINT_MAX);
	printf("n: %d\n", n);
	n = _printf("%#X\n", 1024);
	printf("n: %d\n", n);
	n = _printf("%#X\n", 0);
	printf("n: %d\n", n);
	n = _printf("%#X\n", UINT_MAX);
	printf("n: %d\n", n);
	n = _printf("% ");
	printf("n: %d\n", n);
	_printf("% % % % ");
	printf("n: %d\n", n);
	n = _printf("%06d\n", 102498402);
	printf("n: %d\n", n);
	n = _printf("%06d\n", -102498402);
	printf("n: %d\n", n);
	n = _printf("%06d\n", 0);
	printf("n: %d\n", n);
	n = _printf("%06d\n", 1024);
	printf("n: %d\n", n);
	n = _printf("%06d\n", -1024);
	printf("n: %d\n", n);
	n = _printf("In the middle %06d of a sentence.\n", 1024);
	printf("n: %d\n", n);
	n = _printf("%06i\n", 102498402);
	printf("n: %d\n", n);
	n = _printf("%06i\n", -102498402);
	printf("n: %d\n", n);
	n = _printf("%06i\n", 0);
	printf("n: %d\n", n);
	n = _printf("%06i\n", 1024);
	printf("n: %d\n", n);
	n = _printf("%06i\n", -1024);
	printf("n: %d\n", n);
	n = _printf("In the middle %06i of a sentence.\n", 1024);
	printf("n: %d\n", n);
	n = _printf("%06u\n", 102498402);
	printf("n: %d\n", n);
	n = _printf("%06u\n", 0);
	printf("n: %d\n", n);
	n = _printf("%06u\n", 1024);
	printf("n: %d\n", n);
	n = _printf("In the middle %06u of a sentence.\n", 1024);
	printf("n: %d\n", n);
	n = _printf("%06o\n", 102498402);
	printf("n: %d\n", n);
	n = _printf("%06o\n", 0);
	printf("n: %d\n", n);
	n = _printf("%06o\n", 1024);
	printf("n: %d\n", n);
	n = _printf("In the middle %06o of a sentence.\n", 1024);
	printf("n: %d\n", n);
	n = _printf("%06x\n", 102498402);
	printf("n: %d\n", n);
	n = _printf("%06x\n", 0);
	printf("n: %d\n", n);
	n = _printf("%06x\n", 1024);
	printf("n: %d\n", n);
	n = _printf("In the middle %06x of a sentence.\n", 1024);
	printf("n: %d\n", n);
	n = _printf("%06X\n", 102498402);
	printf("n: %d\n", n);
	n = _printf("%06X\n", 0);
	printf("n: %d\n", n);
	n = _printf("%06X\n", 1024);
	printf("n: %d\n", n);
	n = _printf("In the middle %06X of a sentence.\n", 1024);
	printf("n: %d\n", n);
	n = _printf("%-6d\n", 102498402);
	printf("n: %d\n", n);
	n = _printf("%-6d\n", -102498402);
	printf("n: %d\n", n);
	n = _printf("%-6d\n", 0);
	printf("n: %d\n", n);
	n = _printf("%-6d\n", 1024);
	printf("n: %d\n", n);
	n = _printf("%-6d\n", -1024);
	printf("n: %d\n", n);
	n = _printf("In the middle %-6d of a sentence.\n", 1024);
	printf("n: %d\n", n);
	n = _printf("%-6i\n", 102498402);
	printf("n: %d\n", n);
	n = _printf("%-6i\n", -102498402);
	printf("n: %d\n", n);
	n = _printf("%-6i\n", 0);
	printf("n: %d\n", n);
	n = _printf("%-6i\n", 1024);
	printf("n: %d\n", n);
	n = _printf("%-6i\n", -1024);
	printf("n: %d\n", n);
	n = _printf("In the middle %-6i of a sentence.\n", 1024);
	printf("n: %d\n", n);
	n = _printf("%-6u\n", 102498402);
	printf("n: %d\n", n);
	n = _printf("%-6u\n", 0);
	printf("n: %d\n", n);
	n = _printf("%-6u\n", 1024);
	printf("n: %d\n", n);
	n = _printf("In the middle %-6u of a sentence.\n", 1024);
	printf("n: %d\n", n);
	n = _printf("%-6o\n", 102498402);
	printf("n: %d\n", n);
	n = _printf("%-6o\n", 0);
	printf("n: %d\n", n);
	n = _printf("%-6o\n", 1024);
	printf("n: %d\n", n);
	n = _printf("In the middle %-6o of a sentence.\n", 1024);
	printf("n: %d\n", n);
	n = _printf("%-6x\n", 102498402);
	printf("n: %d\n", n);
	n = _printf("%-6x\n", 0);
	printf("n: %d\n", n);
	n = _printf("%-6x\n", 1024);
	printf("n: %d\n", n);
	n = _printf("In the middle %-6x of a sentence.\n", 1024);
	printf("n: %d\n", n);
	n = _printf("%-6X\n", 102498402);
	printf("n: %d\n", n);
	n = _printf("%-6X\n", 0);
	printf("n: %d\n", n);
	n = _printf("%-6X\n", 1024);
	printf("n: %d\n", n);
	n = _printf("In the middle %-6X of a sentence.\n", 1024);
	printf("n: %d\n", n);


	printf("==============================================\n");


	puts("[The C `printf`]");
	puts("=========");

	n = printf("%+d\n", 1024);
	printf("n: %d\n", n);
	n = printf("%+d\n", -1024);
	printf("n: %d\n", n);
	n = printf("%+d\n", 0);
	printf("n: %d\n", n);
	n = printf("%+d\n", INT_MAX);
	printf("n: %d\n", n);
	n = printf("%+d\n", INT_MIN);
	printf("n: %d\n", n);
	l = INT_MAX + 1024;
	n = printf("%+d\n", l); /* where l is a long int equals to INT_MAX + 1024 */
	printf("n: %d\n", n);
	l = INT_MIN - 1024;
	n = printf("%+d\n", l); /* where l is a long int equals to INT_MIN - 1024 */
	printf("n: %d\n", n);
	n = printf("There is %+d bytes in %+d KB\n", 1024, 1);
	printf("n: %d\n", n);
	n = printf("%+d - %+d = %+d\n", 1024, 2048, -1024);
	printf("n: %d\n", n);
	n = printf("%+d + %+d = %+d\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX));
	printf("n: %d\n", n);
	n = printf("%+i\n", 1024);
	printf("n: %d\n", n);
	n = printf("%+i\n", -1024);
	printf("n: %d\n", n);
	n = printf("%+i\n", 0);
	printf("n: %d\n", n);
	n = printf("%+i\n", INT_MAX);
	printf("n: %d\n", n);
	n = printf("%+i\n", INT_MIN);
	printf("n: %d\n", n);
	l = INT_MAX + 1024;
	n = printf("%+i\n", l); /* where l is a long int equals to INT_MAX + 1024 */
	printf("n: %d\n", n);
	l = INT_MIN - 1024;
	n = printf("%+i\n", l); /* where l is a long int equals to INT_MIN - 1024 */
	printf("n: %d\n", n);
	n = printf("There is %+i bytes in %+i KB\n", 1024, 1);
	printf("n: %d\n", n);
	n = printf("%+i - %+i = %+i\n", 1024, 2048, -1024);
	printf("n: %d\n", n);
	n = printf("%+i + %+i = %+i\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX));
	printf("n: %d\n", n);
	n = printf("% d\n", 1024);
	printf("n: %d\n", n);
	n = printf("% d\n", -1024);
	printf("n: %d\n", n);
	n = printf("% d\n", 0);
	printf("n: %d\n", n);
	n = printf("% d\n", INT_MAX);
	printf("n: %d\n", n);
	n = printf("% d\n", INT_MIN);
	printf("n: %d\n", n);
	l = INT_MAX + 1024;
	n = printf("% d\n", l); /* where l is a long int equals to INT_MAX + 1024 */
	printf("n: %d\n", n);
	l = INT_MIN - 1024;
	n = printf("% d\n", l); /* where l is a long int equals to INT_MIN - 1024 */
	printf("n: %d\n", n);
	n = printf("There is % d bytes in % d KB\n", 1024, 1);
	printf("n: %d\n", n);
	n = printf("% d - % d = % d\n", 1024, 2048, -1024);
	printf("n: %d\n", n);
	n = printf("% d + % d = % d\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX));
	printf("n: %d\n", n);
	n = printf("% i\n", 1024);
	printf("n: %d\n", n);
	n = printf("% i\n", -1024);
	printf("n: %d\n", n);
	n = printf("% i\n", 0);
	printf("n: %d\n", n);
	n = printf("% i\n", INT_MAX);
	printf("n: %d\n", n);
	n = printf("% i\n", INT_MIN);
	printf("n: %d\n", n);
	l = INT_MAX + 1024;
	n = printf("% i\n", l); /* where l is a long int equals to INT_MAX + 1024 */
	printf("n: %d\n", n);
	l = INT_MIN - 1024;
	n = printf("% i\n", l); /* where l is a long int equals to INT_MIN - 1024 */
	printf("n: %d\n", n);
	n = printf("There is % i bytes in % i KB\n", 1024, 1);
	printf("n: %d\n", n);
	n = printf("% i - % i = % i\n", 1024, 2048, -1024);
	printf("n: %d\n", n);
	n = printf("% i + % i = % i\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX));
	printf("n: %d\n", n);
	n = printf("% +i + %+ i = % +d\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX));
	printf("n: %d\n", n);
	n = printf("% +d + %+ d = % +i\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX));
	printf("n: %d\n", n);
	n = printf("%#o\n", 1024);
	printf("n: %d\n", n);
	n = printf("%#o\n", 0);
	printf("n: %d\n", n);
	n = printf("%#o\n", UINT_MAX);
	printf("n: %d\n", n);
	n = printf("%#x\n", 1024);
	printf("n: %d\n", n);
	n = printf("%#x\n", 0);
	printf("n: %d\n", n);
	n = printf("%#x\n", UINT_MAX);
	printf("n: %d\n", n);
	n = printf("%#X\n", 1024);
	printf("n: %d\n", n);
	n = printf("%#X\n", 0);
	printf("n: %d\n", n);
	n = printf("%#X\n", UINT_MAX);
	printf("n: %d\n", n);
	n = printf("% ");
	printf("n: %d\n", n);
	_printf("% % % % ");
	printf("n: %d\n", n);
	n = printf("%06d\n", 102498402);
	printf("n: %d\n", n);
	n = printf("%06d\n", -102498402);
	printf("n: %d\n", n);
	n = printf("%06d\n", 0);
	printf("n: %d\n", n);
	n = printf("%06d\n", 1024);
	printf("n: %d\n", n);
	n = printf("%06d\n", -1024);
	printf("n: %d\n", n);
	n = printf("In the middle %06d of a sentence.\n", 1024);
	printf("n: %d\n", n);
	n = printf("%06i\n", 102498402);
	printf("n: %d\n", n);
	n = printf("%06i\n", -102498402);
	printf("n: %d\n", n);
	n = printf("%06i\n", 0);
	printf("n: %d\n", n);
	n = printf("%06i\n", 1024);
	printf("n: %d\n", n);
	n = printf("%06i\n", -1024);
	printf("n: %d\n", n);
	n = printf("In the middle %06i of a sentence.\n", 1024);
	printf("n: %d\n", n);
	n = printf("%06u\n", 102498402);
	printf("n: %d\n", n);
	n = printf("%06u\n", 0);
	printf("n: %d\n", n);
	n = printf("%06u\n", 1024);
	printf("n: %d\n", n);
	n = printf("In the middle %06u of a sentence.\n", 1024);
	printf("n: %d\n", n);
	n = printf("%06o\n", 102498402);
	printf("n: %d\n", n);
	n = printf("%06o\n", 0);
	printf("n: %d\n", n);
	n = printf("%06o\n", 1024);
	printf("n: %d\n", n);
	n = printf("In the middle %06o of a sentence.\n", 1024);
	printf("n: %d\n", n);
	n = printf("%06x\n", 102498402);
	printf("n: %d\n", n);
	n = printf("%06x\n", 0);
	printf("n: %d\n", n);
	n = printf("%06x\n", 1024);
	printf("n: %d\n", n);
	n = printf("In the middle %06x of a sentence.\n", 1024);
	printf("n: %d\n", n);
	n = printf("%06X\n", 102498402);
	printf("n: %d\n", n);
	n = printf("%06X\n", 0);
	printf("n: %d\n", n);
	n = printf("%06X\n", 1024);
	printf("n: %d\n", n);
	n = printf("In the middle %06X of a sentence.\n", 1024);
	printf("n: %d\n", n);
	n = printf("%-6d\n", 102498402);
	printf("n: %d\n", n);
	n = printf("%-6d\n", -102498402);
	printf("n: %d\n", n);
	n = printf("%-6d\n", 0);
	printf("n: %d\n", n);
	n = printf("%-6d\n", 1024);
	printf("n: %d\n", n);
	n = printf("%-6d\n", -1024);
	printf("n: %d\n", n);
	n = printf("In the middle %-6d of a sentence.\n", 1024);
	printf("n: %d\n", n);
	n = printf("%-6i\n", 102498402);
	printf("n: %d\n", n);
	n = printf("%-6i\n", -102498402);
	printf("n: %d\n", n);
	n = printf("%-6i\n", 0);
	printf("n: %d\n", n);
	n = printf("%-6i\n", 1024);
	printf("n: %d\n", n);
	n = printf("%-6i\n", -1024);
	printf("n: %d\n", n);
	n = printf("In the middle %-6i of a sentence.\n", 1024);
	printf("n: %d\n", n);
	n = printf("%-6u\n", 102498402);
	printf("n: %d\n", n);
	n = printf("%-6u\n", 0);
	printf("n: %d\n", n);
	n = printf("%-6u\n", 1024);
	printf("n: %d\n", n);
	n = printf("In the middle %-6u of a sentence.\n", 1024);
	printf("n: %d\n", n);
	n = printf("%-6o\n", 102498402);
	printf("n: %d\n", n);
	n = printf("%-6o\n", 0);
	printf("n: %d\n", n);
	n = printf("%-6o\n", 1024);
	printf("n: %d\n", n);
	n = printf("In the middle %-6o of a sentence.\n", 1024);
	printf("n: %d\n", n);
	n = printf("%-6x\n", 102498402);
	printf("n: %d\n", n);
	n = printf("%-6x\n", 0);
	printf("n: %d\n", n);
	n = printf("%-6x\n", 1024);
	printf("n: %d\n", n);
	n = printf("In the middle %-6x of a sentence.\n", 1024);
	printf("n: %d\n", n);
	n = printf("%-6X\n", 102498402);
	printf("n: %d\n", n);
	n = printf("%-6X\n", 0);
	printf("n: %d\n", n);
	n = printf("%-6X\n", 1024);
	printf("n: %d\n", n);
	n = printf("In the middle %-6X of a sentence.\n", 1024);
	printf("n: %d\n", n);



	return (0);
}
