#include <stdio.h>
#include <limits.h>
#include "../main.h"

/**
 * main - Entry point
 *
 * Return: Always 0
 */
int main(void)
{
	int n;

	puts("[My `_printf`]");
	puts("=========");

	n = _printf("%6d\n", 102498402);
	printf("n: %d\n", n);
	n = _printf("%6d\n", -102498402);
	printf("n: %d\n", n);
	n = _printf("%6d\n", 0);
	printf("n: %d\n", n);
	n = _printf("%6d\n", 1024);
	printf("n: %d\n", n);
	n = _printf("%6d\n", -1024);
	printf("n: %d\n", n);
	n = _printf("In the middle %6d of a sentence.\n", 1024);
	printf("n: %d\n", n);
	n = _printf("%6i\n", 102498402);
	printf("n: %d\n", n);
	n = _printf("%6i\n", -102498402);
	printf("n: %d\n", n);
	n = _printf("%6i\n", 0);
	printf("n: %d\n", n);
	n = _printf("%6i\n", 1024);
	printf("n: %d\n", n);
	n = _printf("%6i\n", -1024);
	printf("n: %d\n", n);
	n = _printf("In the middle %6i of a sentence.\n", 1024);
	printf("n: %d\n", n);
	n = _printf("%6u\n", 102498402);
	printf("n: %d\n", n);
	n = _printf("%6u\n", 0);
	printf("n: %d\n", n);
	n = _printf("%6u\n", 1024);
	printf("n: %d\n", n);
	n = _printf("In the middle %6u of a sentence.\n", 1024);
	printf("n: %d\n", n);
	n = _printf("%6o\n", 102498402);
	printf("n: %d\n", n);
	n = _printf("%6o\n", 0);
	printf("n: %d\n", n);
	n = _printf("%6o\n", 1024);
	printf("n: %d\n", n);
	n = _printf("In the middle %6o of a sentence.\n", 1024);
	printf("n: %d\n", n);
	n = _printf("%6x\n", 102498402);
	printf("n: %d\n", n);
	n = _printf("%6x\n", 0);
	printf("n: %d\n", n);
	n = _printf("%6x\n", 1024);
	printf("n: %d\n", n);
	n = _printf("In the middle %6x of a sentence.\n", 1024);
	printf("n: %d\n", n);
	n = _printf("%6X\n", 102498402);
	printf("n: %d\n", n);
	n = _printf("%6X\n", 0);
	printf("n: %d\n", n);
	n = _printf("%6X\n", 1024);
	printf("n: %d\n", n);
	n = _printf("In the middle %6X of a sentence.\n", 1024);
	printf("n: %d\n", n);
	n = _printf("%6c\n", 'A');
	printf("n: %d\n", n);
	n = _printf("%6c\n", 0);
	printf("n: %d\n", n);
	n = _printf("In the middle %6c of a sentence.\n", 'H');
	printf("n: %d\n", n);
	n = _printf("%6s\n", "Best School !\n");
	printf("n: %d\n", n);
	n = _printf("%6s\n", "Hi!\n");
	printf("n: %d\n", n);
	n = _printf("In the middle %6s of a sentence.\n", "Hey");
	printf("n: %d\n", n);
	n = _printf("%*d\n", 6, 102498402);
	printf("n: %d\n", n);
	n = _printf("%*d\n", 6, -102498402);
	printf("n: %d\n", n);
	n = _printf("%*d\n", 6, 0);
	printf("n: %d\n", n);
	n = _printf("%*d\n", 6, 1024);
	printf("n: %d\n", n);
	n = _printf("%*d\n", 6, -1024);
	printf("n: %d\n", n);
	n = _printf("In the middle %*d of a sentence.\n", 6, 1024);
	printf("n: %d\n", n);
	n = _printf("%*i\n", 6, 102498402);
	printf("n: %d\n", n);
	n = _printf("%*i\n", 6, -102498402);
	printf("n: %d\n", n);
	n = _printf("%*i\n", 6, 0);
	printf("n: %d\n", n);
	n = _printf("%*i\n", 6, 1024);
	printf("n: %d\n", n);
	n = _printf("%*i\n", 6, -1024);
	printf("n: %d\n", n);
	n = _printf("In the middle %*i of a sentence.\n", 6, 1024);
	printf("n: %d\n", n);
	n = _printf("%*u\n", 6, 102498402);
	printf("n: %d\n", n);
	n = _printf("%*u\n", 6, 0);
	printf("n: %d\n", n);
	n = _printf("%*u\n", 6, 1024);
	printf("n: %d\n", n);
	n = _printf("In the middle %*u of a sentence.\n", 6, 1024);
	printf("n: %d\n", n);
	n = _printf("%*o\n", 6, 102498402);
	printf("n: %d\n", n);
	n = _printf("%*o\n", 6, 0);
	printf("n: %d\n", n);
	n = _printf("%*o\n", 6, 1024);
	printf("n: %d\n", n);
	n = _printf("In the middle %*o of a sentence.\n", 6, 1024);
	printf("n: %d\n", n);
	n = _printf("%*x\n", 6, 102498402);
	printf("n: %d\n", n);
	n = _printf("%*x\n", 6, 0);
	printf("n: %d\n", n);
	n = _printf("%*x\n", 6, 1024);
	printf("n: %d\n", n);
	n = _printf("In the middle %*x of a sentence.\n", 6, 1024);
	printf("n: %d\n", n);
	n = _printf("%*X\n", 6, 102498402);
	printf("n: %d\n", n);
	n = _printf("%*X\n", 6, 0);
	printf("n: %d\n", n);
	n = _printf("%*X\n", 6, 1024);
	printf("n: %d\n", n);
	n = _printf("In the middle %*X of a sentence.\n", 6, 1024);
	printf("n: %d\n", n);
	n = _printf("%*c\n", 6, 'A');
	printf("n: %d\n", n);
	n = _printf("%*c\n", 6, 0);
	printf("n: %d\n", n);
	n = _printf("In the middle %*c of a sentence.\n", 6, 'H');
	printf("n: %d\n", n);
	n = _printf("%*s\n", 6, "Best School !\n");
	printf("n: %d\n", n);
	n = _printf("%*s\n", 6, "Hi!\n");
	printf("n: %d\n", n);
	n = _printf("In the middle %*s of a sentence.\n", 6, "Hey");
	printf("n: %d\n", n);


	printf("==============================================\n");


	puts("[The C `printf`]");
	puts("=========");

	n = printf("%6d\n", 102498402);
	printf("n: %d\n", n);
	n = printf("%6d\n", -102498402);
	printf("n: %d\n", n);
	n = printf("%6d\n", 0);
	printf("n: %d\n", n);
	n = printf("%6d\n", 1024);
	printf("n: %d\n", n);
	n = printf("%6d\n", -1024);
	printf("n: %d\n", n);
	n = printf("In the middle %6d of a sentence.\n", 1024);
	printf("n: %d\n", n);
	n = printf("%6i\n", 102498402);
	printf("n: %d\n", n);
	n = printf("%6i\n", -102498402);
	printf("n: %d\n", n);
	n = printf("%6i\n", 0);
	printf("n: %d\n", n);
	n = printf("%6i\n", 1024);
	printf("n: %d\n", n);
	n = printf("%6i\n", -1024);
	printf("n: %d\n", n);
	n = printf("In the middle %6i of a sentence.\n", 1024);
	printf("n: %d\n", n);
	n = printf("%6u\n", 102498402);
	printf("n: %d\n", n);
	n = printf("%6u\n", 0);
	printf("n: %d\n", n);
	n = printf("%6u\n", 1024);
	printf("n: %d\n", n);
	n = printf("In the middle %6u of a sentence.\n", 1024);
	printf("n: %d\n", n);
	n = printf("%6o\n", 102498402);
	printf("n: %d\n", n);
	n = printf("%6o\n", 0);
	printf("n: %d\n", n);
	n = printf("%6o\n", 1024);
	printf("n: %d\n", n);
	n = printf("In the middle %6o of a sentence.\n", 1024);
	printf("n: %d\n", n);
	n = printf("%6x\n", 102498402);
	printf("n: %d\n", n);
	n = printf("%6x\n", 0);
	printf("n: %d\n", n);
	n = printf("%6x\n", 1024);
	printf("n: %d\n", n);
	n = printf("In the middle %6x of a sentence.\n", 1024);
	printf("n: %d\n", n);
	n = printf("%6X\n", 102498402);
	printf("n: %d\n", n);
	n = printf("%6X\n", 0);
	printf("n: %d\n", n);
	n = printf("%6X\n", 1024);
	printf("n: %d\n", n);
	n = printf("In the middle %6X of a sentence.\n", 1024);
	printf("n: %d\n", n);
	n = printf("%6c\n", 'A');
	printf("n: %d\n", n);
	n = printf("%6c\n", 0);
	printf("n: %d\n", n);
	n = printf("In the middle %6c of a sentence.\n", 'H');
	printf("n: %d\n", n);
	n = printf("%6s\n", "Best School !\n");
	printf("n: %d\n", n);
	n = printf("%6s\n", "Hi!\n");
	printf("n: %d\n", n);
	n = printf("In the middle %6s of a sentence.\n", "Hey");
	printf("n: %d\n", n);
	n = printf("%*d\n", 6, 102498402);
	printf("n: %d\n", n);
	n = printf("%*d\n", 6, -102498402);
	printf("n: %d\n", n);
	n = printf("%*d\n", 6, 0);
	printf("n: %d\n", n);
	n = printf("%*d\n", 6, 1024);
	printf("n: %d\n", n);
	n = printf("%*d\n", 6, -1024);
	printf("n: %d\n", n);
	n = printf("In the middle %*d of a sentence.\n", 6, 1024);
	printf("n: %d\n", n);
	n = printf("%*i\n", 6, 102498402);
	printf("n: %d\n", n);
	n = printf("%*i\n", 6, -102498402);
	printf("n: %d\n", n);
	n = printf("%*i\n", 6, 0);
	printf("n: %d\n", n);
	n = printf("%*i\n", 6, 1024);
	printf("n: %d\n", n);
	n = printf("%*i\n", 6, -1024);
	printf("n: %d\n", n);
	n = printf("In the middle %*i of a sentence.\n", 6, 1024);
	printf("n: %d\n", n);
	n = printf("%*u\n", 6, 102498402);
	printf("n: %d\n", n);
	n = printf("%*u\n", 6, 0);
	printf("n: %d\n", n);
	n = printf("%*u\n", 6, 1024);
	printf("n: %d\n", n);
	n = printf("In the middle %*u of a sentence.\n", 6, 1024);
	printf("n: %d\n", n);
	n = printf("%*o\n", 6, 102498402);
	printf("n: %d\n", n);
	n = printf("%*o\n", 6, 0);
	printf("n: %d\n", n);
	n = printf("%*o\n", 6, 1024);
	printf("n: %d\n", n);
	n = printf("In the middle %*o of a sentence.\n", 6, 1024);
	printf("n: %d\n", n);
	n = printf("%*x\n", 6, 102498402);
	printf("n: %d\n", n);
	n = printf("%*x\n", 6, 0);
	printf("n: %d\n", n);
	n = printf("%*x\n", 6, 1024);
	printf("n: %d\n", n);
	n = printf("In the middle %*x of a sentence.\n", 6, 1024);
	printf("n: %d\n", n);
	n = printf("%*X\n", 6, 102498402);
	printf("n: %d\n", n);
	n = printf("%*X\n", 6, 0);
	printf("n: %d\n", n);
	n = printf("%*X\n", 6, 1024);
	printf("n: %d\n", n);
	n = printf("In the middle %*X of a sentence.\n", 6, 1024);
	printf("n: %d\n", n);
	n = printf("%*c\n", 6, 'A');
	printf("n: %d\n", n);
	n = printf("%*c\n", 6, 0);
	printf("n: %d\n", n);
	n = printf("In the middle %*c of a sentence.\n", 6, 'H');
	printf("n: %d\n", n);
	n = printf("%*s\n", 6, "Best School !\n");
	printf("n: %d\n", n);
	n = printf("%*s\n", 6, "Hi!\n");
	printf("n: %d\n", n);
	n = printf("In the middle %*s of a sentence.\n", 6, "Hey");
	printf("n: %d\n", n);



	return (0);
}
