#include <stdio.h>
#include <limits.h>
#include "../main.h"

/**
 * main - Entry point
 *
 * Return: Always 0
 */
int main(void)
{
	int n;

	puts("[My `_printf`]");
	puts("=========");

	n = _printf("%ld\n", 1024L);
	printf("n: %d\n", n);
	n = _printf("%ld\n", -1024L);
	printf("n: %d\n", n);
	n = _printf("%ld\n", 0L);
	printf("n: %d\n", n);
	n = _printf("%ld\n", LONG_MAX);
	printf("n: %d\n", n);
	n = _printf("%ld\n", LONG_MIN);
	printf("n: %d\n", n);
	n = _printf("There is %ld bytes in %ld KB\n", 1024L, 1L);
	printf("n: %d\n", n);
	n = _printf("%ld - %ld = %ld\n", 1024L, 2048L, -1024L);
	printf("n: %d\n", n);
	n = _printf("%ld + %ld = %ld\n", LONG_MIN, LONG_MAX, (LONG_MIN + LONG_MAX));
	printf("n: %d\n", n);
	n = _printf("%li\n", 1024L);
	printf("n: %d\n", n);
	n = _printf("%li\n", -1024L);
	printf("n: %d\n", n);
	n = _printf("%li\n", 0L);
	printf("n: %d\n", n);
	n = _printf("%li\n", LONG_MAX);
	printf("n: %d\n", n);
	n = _printf("%li\n", LONG_MIN);
	printf("n: %d\n", n);
	n = _printf("There is %li bytes in %li KB\n", 1024L, 1L);
	printf("n: %d\n", n);
	n = _printf("%li - %li = %li\n", 1024L, 2048L, -1024L);
	printf("n: %d\n", n);
	n = _printf("%li + %li = %li\n", LONG_MIN, LONG_MAX, (LONG_MIN + LONG_MAX));
	printf("n: %d\n", n);
	n = _printf("%lu\n", 1024UL);
	printf("n: %d\n", n);
	n = _printf("%lu\n", 0UL);
	printf("n: %d\n", n);
	n = _printf("%lu\n", ULONG_MAX);
	printf("n: %d\n", n);
	n = _printf("There is %lu bytes in %lu KB\n", 1024UL, 1UL);
	printf("n: %d\n", n);
	n = _printf("%lu - %lu = %lu\n", ULONG_MAX, 2048UL, ULONG_MAX - 2048UL);
	printf("n: %d\n", n);
	n = _printf("%lo\n", 1024UL);
	printf("n: %d\n", n);
	n = _printf("%lo\n", 0UL);
	printf("n: %d\n", n);
	n = _printf("%lo\n", ULONG_MAX);
	printf("n: %d\n", n);
	n = _printf("There is %lo bytes in %lo KB\n", 1024UL, 1UL);
	printf("n: %d\n", n);
	n = _printf("%lo - %lo = %lo\n", ULONG_MAX, 2048UL, ULONG_MAX - 2048UL);
	printf("n: %d\n", n);
	n = _printf("%lx\n", 1024UL);
	printf("n: %d\n", n);
	n = _printf("%lx\n", 0UL);
	printf("n: %d\n", n);
	n = _printf("%lx\n", ULONG_MAX);
	printf("n: %d\n", n);
	n = _printf("There is %lx bytes in %lx KB\n", 1024UL, 1UL);
	printf("n: %d\n", n);
	n = _printf("%lx - %lx = %lx\n", ULONG_MAX, 2048UL, ULONG_MAX - 2048UL);
	printf("n: %d\n", n);
	n = _printf("%lX\n", 1024UL);
	printf("n: %d\n", n);
	n = _printf("%lX\n", 0UL);
	printf("n: %d\n", n);
	n = _printf("%lX\n", ULONG_MAX);
	printf("n: %d\n", n);
	n = _printf("There is %lX bytes in %lX KB\n", 1024UL, 1UL);
	printf("n: %d\n", n);
	n = _printf("%lX - %lX = %lX\n", ULONG_MAX, 2048UL, ULONG_MAX - 2048UL);
	printf("n: %d\n", n);
	n = _printf("%hd\n", 1024);
	printf("n: %d\n", n);
	n = _printf("%hd\n", -1024);
	printf("n: %d\n", n);
	n = _printf("%hd\n", 0);
	printf("n: %d\n", n);
	n = _printf("%hd\n", SHRT_MAX);
	printf("n: %d\n", n);
	n = _printf("%hd\n", SHRT_MIN);
	printf("n: %d\n", n);
	n = _printf("There is %hd bytes in %hd KB\n", 1024, 1);
	printf("n: %d\n", n);
	n = _printf("%hd - %hd = %hd\n", 1024, 2048, -1024);
	printf("n: %d\n", n);
	n = _printf("%hd + %hd = %hd\n", SHRT_MIN, SHRT_MAX, (SHRT_MIN + SHRT_MAX));
	printf("n: %d\n", n);
	n = _printf("%hi\n", 1024);
	printf("n: %d\n", n);
	n = _printf("%hi\n", -1024);
	printf("n: %d\n", n);
	n = _printf("%hi\n", 0);
	printf("n: %d\n", n);
	n = _printf("%hi\n", SHRT_MAX);
	printf("n: %d\n", n);
	n = _printf("%hi\n", SHRT_MIN);
	printf("n: %d\n", n);
	n = _printf("There is %hi bytes in %hi KB\n", 1024, 1);
	printf("n: %d\n", n);
	n = _printf("%hi - %hi = %hi\n", 1024, 2048, -1024);
	printf("n: %d\n", n);
	n = _printf("%hi + %hi = %hi\n", SHRT_MIN, SHRT_MAX, (SHRT_MIN + SHRT_MAX));
	printf("n: %d\n", n);
	n = _printf("%hu\n", 1024);
	printf("n: %d\n", n);
	n = _printf("%hu\n", 0);
	printf("n: %d\n", n);
	n = _printf("%hu\n", USHRT_MAX);
	printf("n: %d\n", n);
	n = _printf("There is %hu bytes in %hu KB\n", 1024, 1);
	printf("n: %d\n", n);
	n = _printf("%hu - %hu = %hu\n", USHRT_MAX, 2048, USHRT_MAX - 2048);
	printf("n: %d\n", n);
	n = _printf("%ho\n", 1024);
	printf("n: %d\n", n);
	n = _printf("%ho\n", 0);
	printf("n: %d\n", n);
	n = _printf("%ho\n", USHRT_MAX);
	printf("n: %d\n", n);
	n = _printf("There is %ho bytes in %ho KB\n", 1024, 1);
	printf("n: %d\n", n);
	n = _printf("%ho - %ho = %ho\n", USHRT_MAX, 2048, USHRT_MAX - 2048);
	printf("n: %d\n", n);
	n = _printf("%hx\n", 1024);
	printf("n: %d\n", n);
	n = _printf("%hx\n", 0);
	printf("n: %d\n", n);
	n = _printf("%hx\n", USHRT_MAX);
	printf("n: %d\n", n);
	n = _printf("There is %hx bytes in %hx KB\n", 1024, 1);
	printf("n: %d\n", n);
	n = _printf("%hx - %hx = %hx\n", USHRT_MAX, 2048, USHRT_MAX - 2048);
	printf("n: %d\n", n);
	n = _printf("%hX\n", 1024);
	printf("n: %d\n", n);
	n = _printf("%hX\n", 0);
	printf("n: %d\n", n);
	n = _printf("%hX\n", USHRT_MAX);
	printf("n: %d\n", n);
	n = _printf("There is %hX bytes in %hX KB\n", 1024, 1);
	printf("n: %d\n", n);
	n = _printf("%hX - %hX = %hX\n", USHRT_MAX, 2048, USHRT_MAX - 2048);
	printf("n: %d\n", n);
	n = _printf("%h\n");
	printf("n: %d\n", n);
	n = _printf("%l\n");
	printf("n: %d\n", n);


	printf("==============================================\n");


	puts("[The C `printf`]");
	puts("=========");

	n = printf("%ld\n", 1024L);
	printf("n: %d\n", n);
	n = printf("%ld\n", -1024L);
	printf("n: %d\n", n);
	n = printf("%ld\n", 0L);
	printf("n: %d\n", n);
	n = printf("%ld\n", LONG_MAX);
	printf("n: %d\n", n);
	n = printf("%ld\n", LONG_MIN);
	printf("n: %d\n", n);
	n = printf("There is %ld bytes in %ld KB\n", 1024L, 1L);
	printf("n: %d\n", n);
	n = printf("%ld - %ld = %ld\n", 1024L, 2048L, -1024L);
	printf("n: %d\n", n);
	n = printf("%ld + %ld = %ld\n", LONG_MIN, LONG_MAX, (LONG_MIN + LONG_MAX));
	printf("n: %d\n", n);
	n = printf("%li\n", 1024L);
	printf("n: %d\n", n);
	n = printf("%li\n", -1024L);
	printf("n: %d\n", n);
	n = printf("%li\n", 0L);
	printf("n: %d\n", n);
	n = printf("%li\n", LONG_MAX);
	printf("n: %d\n", n);
	n = printf("%li\n", LONG_MIN);
	printf("n: %d\n", n);
	n = printf("There is %li bytes in %li KB\n", 1024L, 1L);
	printf("n: %d\n", n);
	n = printf("%li - %li = %li\n", 1024L, 2048L, -1024L);
	printf("n: %d\n", n);
	n = printf("%li + %li = %li\n", LONG_MIN, LONG_MAX, (LONG_MIN + LONG_MAX));
	printf("n: %d\n", n);
	n = printf("%lu\n", 1024UL);
	printf("n: %d\n", n);
	n = printf("%lu\n", 0UL);
	printf("n: %d\n", n);
	n = printf("%lu\n", ULONG_MAX);
	printf("n: %d\n", n);
	n = printf("There is %lu bytes in %lu KB\n", 1024UL, 1UL);
	printf("n: %d\n", n);
	n = printf("%lu - %lu = %lu\n", ULONG_MAX, 2048UL, ULONG_MAX - 2048UL);
	printf("n: %d\n", n);
	n = printf("%lo\n", 1024UL);
	printf("n: %d\n", n);
	n = printf("%lo\n", 0UL);
	printf("n: %d\n", n);
	n = printf("%lo\n", ULONG_MAX);
	printf("n: %d\n", n);
	n = printf("There is %lo bytes in %lo KB\n", 1024UL, 1UL);
	printf("n: %d\n", n);
	n = printf("%lo - %lo = %lo\n", ULONG_MAX, 2048UL, ULONG_MAX - 2048UL);
	printf("n: %d\n", n);
	n = printf("%lx\n", 1024UL);
	printf("n: %d\n", n);
	n = printf("%lx\n", 0UL);
	printf("n: %d\n", n);
	n = printf("%lx\n", ULONG_MAX);
	printf("n: %d\n", n);
	n = printf("There is %lx bytes in %lx KB\n", 1024UL, 1UL);
	printf("n: %d\n", n);
	n = printf("%lx - %lx = %lx\n", ULONG_MAX, 2048UL, ULONG_MAX - 2048UL);
	printf("n: %d\n", n);
	n = printf("%lX\n", 1024UL);
	printf("n: %d\n", n);
	n = printf("%lX\n", 0UL);
	printf("n: %d\n", n);
	n = printf("%lX\n", ULONG_MAX);
	printf("n: %d\n", n);
	n = printf("There is %lX bytes in %lX KB\n", 1024UL, 1UL);
	printf("n: %d\n", n);
	n = printf("%lX - %lX = %lX\n", ULONG_MAX, 2048UL, ULONG_MAX - 2048UL);
	printf("n: %d\n", n);
	n = printf("%hd\n", 1024);
	printf("n: %d\n", n);
	n = printf("%hd\n", -1024);
	printf("n: %d\n", n);
	n = printf("%hd\n", 0);
	printf("n: %d\n", n);
	n = printf("%hd\n", SHRT_MAX);
	printf("n: %d\n", n);
	n = printf("%hd\n", SHRT_MIN);
	printf("n: %d\n", n);
	n = printf("There is %hd bytes in %hd KB\n", 1024, 1);
	printf("n: %d\n", n);
	n = printf("%hd - %hd = %hd\n", 1024, 2048, -1024);
	printf("n: %d\n", n);
	n = printf("%hd + %hd = %hd\n", SHRT_MIN, SHRT_MAX, (SHRT_MIN + SHRT_MAX));
	printf("n: %d\n", n);
	n = printf("%hi\n", 1024);
	printf("n: %d\n", n);
	n = printf("%hi\n", -1024);
	printf("n: %d\n", n);
	n = printf("%hi\n", 0);
	printf("n: %d\n", n);
	n = printf("%hi\n", SHRT_MAX);
	printf("n: %d\n", n);
	n = printf("%hi\n", SHRT_MIN);
	printf("n: %d\n", n);
	n = printf("There is %hi bytes in %hi KB\n", 1024, 1);
	printf("n: %d\n", n);
	n = printf("%hi - %hi = %hi\n", 1024, 2048, -1024);
	printf("n: %d\n", n);
	n = printf("%hi + %hi = %hi\n", SHRT_MIN, SHRT_MAX, (SHRT_MIN + SHRT_MAX));
	printf("n: %d\n", n);
	n = printf("%hu\n", 1024);
	printf("n: %d\n", n);
	n = printf("%hu\n", 0);
	printf("n: %d\n", n);
	n = printf("%hu\n", USHRT_MAX);
	printf("n: %d\n", n);
	n = printf("There is %hu bytes in %hu KB\n", 1024, 1);
	printf("n: %d\n", n);
	n = printf("%hu - %hu = %hu\n", USHRT_MAX, 2048, USHRT_MAX - 2048);
	printf("n: %d\n", n);
	n = printf("%ho\n", 1024);
	printf("n: %d\n", n);
	n = printf("%ho\n", 0);
	printf("n: %d\n", n);
	n = printf("%ho\n", USHRT_MAX);
	printf("n: %d\n", n);
	n = printf("There is %ho bytes in %ho KB\n", 1024, 1);
	printf("n: %d\n", n);
	n = printf("%ho - %ho = %ho\n", USHRT_MAX, 2048, USHRT_MAX - 2048);
	printf("n: %d\n", n);
	n = printf("%hx\n", 1024);
	printf("n: %d\n", n);
	n = printf("%hx\n", 0);
	printf("n: %d\n", n);
	n = printf("%hx\n", USHRT_MAX);
	printf("n: %d\n", n);
	n = printf("There is %hx bytes in %hx KB\n", 1024, 1);
	printf("n: %d\n", n);
	n = printf("%hx - %hx = %hx\n", USHRT_MAX, 2048, USHRT_MAX - 2048);
	printf("n: %d\n", n);
	n = printf("%hX\n", 1024);
	printf("n: %d\n", n);
	n = printf("%hX\n", 0);
	printf("n: %d\n", n);
	n = printf("%hX\n", USHRT_MAX);
	printf("n: %d\n", n);
	n = printf("There is %hX bytes in %hX KB\n", 1024, 1);
	printf("n: %d\n", n);
	n = printf("%hX - %hX = %hX\n", USHRT_MAX, 2048, USHRT_MAX - 2048);
	printf("n: %d\n", n);
	n = printf("%h\n");
	printf("n: %d\n", n);
	n = printf("%l\n");
	printf("n: %d\n", n);



	return (0);
}
